apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sports-analytics-database
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 100Gi