apiVersion: v1
kind: Pod
metadata:
  namespace: spatiotemporal-decision-making
  name: muscle-simulation-pod
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
          # - key: topology.kubernetes.io/region
          #   operator: In
          #   values:
          #   - us-west
            - key: nautilus.io/group
              operator: In
              values:
              - ry
  imagePullSecrets:
    - name: shubh-gitlab-registry
  containers:
  - name: shubh-container
    image: gitlab-registry.nrp-nautilus.io/shmaheshwari/sports-analytics:latest
    # image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/minimal
    command: ["/bin/bash","-c"]
    # args: ["cd /vol/se3-transformer-public && chmod +x installs.sh && ./installs.sh && sleep infinity"]
    args: ["cd /mnt/data/ && chmod +x run.sh && /bin/sh run.sh"]

    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /mnt/data
      name: sports-analytics-database
    resources:
      limits:
        nvidia.com/gpu: "1"
        memory: "30G"
        cpu: "4"
        # ephemeral-storage: 1024Gi
      requests:
        nvidia.com/gpu: "1"
        memory: "30G"
        cpu: "4"
  tolerations:
  - key: "nautilus.io/ry-reservation"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"  
  restartPolicy: Never
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
    - name: sports-analytics-database
      persistentVolumeClaim:
        claimName: sports-analytics-database
