apiVersion: v1
kind: Service 
metadata:
  name: syncthing-service # Exposes the Syncthing web GUI port.
spec:
  selector:
    app: syncthing
  ports:
    - protocol: TCP
      port: 8384
      targetPort: 8384
  type: NodePort